# Generated by Django 5.2.1 on 2025-06-25 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='admin_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador de la Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='suscripciones.suscripcion', verbose_name='Plan de Suscripción'),
        ),
    ]
