# Generated by Django 5.2.1 on 2025-06-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion_corta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
