# Generated by Django 5.2.1 on 2025-06-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_empresa_descripcion_corta'),
        ('ventas', '0004_alter_detalleventa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total del pago.', max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el pago.')),
                ('metodo_pago', models.CharField(choices=[('STRIPE', 'Stripe'), ('QR', 'QR (Código QR)'), ('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria')], default='STRIPE', help_text='Método de pago utilizado (ej. Stripe, QR).', max_length=50)),
                ('referencia_transaccion', models.CharField(blank=True, help_text='ID o referencia de la transacción de la pasarela de pago.', max_length=255, null=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='COMPLETADO', help_text='Estado actual del pago (ej. Pendiente, Completado, Fallido).', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente que realizó el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa que recibió el pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_recibidos', to='empresas.empresa')),
                ('venta', models.OneToOneField(blank=True, help_text='Venta asociada a este pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
