# Generated by Django 5.2.1 on 2025-06-27 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_descripcion_corta'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(default=1, help_text='Cliente que realizó el pago.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa que recibe este pago.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró el pago.'),
        ),
    ]
