# Generated by Django 5.2.1 on 2025-06-25 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('activity_type', models.CharField(max_length=100, verbose_name='Tipo de Actividad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Entidad Afectada')),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Entidad Afectada')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-timestamp'],
            },
        ),
    ]
