# Generated by Django 5.2.1 on 2025-06-20 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes', to='sucursales.sucursal', verbose_name='Sucursal Asociada'),
        ),
        migrations.AlterUniqueTogether(
            name='almacen',
            unique_together={('nombre', 'empresa')},
        ),
    ]
