# Generated by Django 5.2.1 on 2025-06-27 03:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0002_initial'),
        ('empresas', '0002_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Llegada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo de Transporte')),
                ('monto_total_operacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Monto Total de la Operación')),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='almacenes.almacen')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='empresas.empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_suministrados', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_llegada'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_suministrada', models.PositiveIntegerField(verbose_name='Cantidad Suministrada')),
                ('colores', models.CharField(blank=True, max_length=200, null=True, verbose_name='Colores Suministrados (ej. Rojo, Azul)')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario de Compra')),
                ('valor_total_producto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total del Producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='movimientos.movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento',
                'verbose_name_plural': 'Detalles de Movimiento',
                'unique_together': {('movimiento', 'producto')},
            },
        ),
    ]
