# Generated by Django 5.2.1 on 2025-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', help_text='Estado actual del movimiento (Pendiente, Aceptado, Rechazado)', max_length=20),
        ),
    ]
