# Generated by Django 5.2.1 on 2025-06-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Descuento Aplicado'),
        ),
    ]
