# Generated by Django 5.2.1 on 2025-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_descuento_aplicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='descuento_aplicado',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, verbose_name='Descuento Aplicado'),
        ),
    ]
