# Generated by Django 5.2.1 on 2025-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_descuento_aplicado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
