# Generated by Django 5.2.1 on 2025-06-27 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_descripcion_corta'),
        ('productos', '0003_producto_is_active_alter_producto_descuento'),
        ('ventas', '0004_alter_detalleventa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('MARKETPLACE', 'Marketplace')], default='MANUAL', help_text='Origen de la venta (Manual, Marketplace).', max_length=50),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.IntegerField(help_text='Cantidad del producto vendido.'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Descuento aplicado por unidad (ej. 0.10 para 10%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario del producto al momento de la venta.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa a la que pertenece esta venta.', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_empresa', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', help_text='Estado actual de la venta (Pendiente, Completada, Cancelada).', max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la venta.'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total de la venta después de descuentos.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la compra (cliente o vendedor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='detalleventa',
            unique_together={('venta', 'producto')},
        ),
    ]
